### ISSUE TITLE
ParseTx Arguments and Return

### ISSUE THREAD

**Issue by juliankoh** [Zondax/rosetta-filecoin-lib#12]
- Can the ParseTx function take a string as argument instead of []byte to be consistent with the other functions?
- Can the ParseTx function return a (string, error) , and handle the parsing from types -> string?

**Comment by jleni** [comment]
in the case of strings... should we expect:
- base64 
- base64/hex or
- other encoding?

**Comment by juliankoh** [comment]
@jleni Lets stick with b64 for consistency. Thanks!

**Comment by rllola** [comment]
@juliankoh Do you think this would also be needed for `SignTx` the privateKey argument is in []byte for consistency maybe have it in base64 and same for the returned value ?
