### ISSUE TITLE
Extend ParseTx to receive network type

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-lib#34]
CBOR blobs do not contain network type information. In order to return a JSON with correctly formatted addresses, an additional network parameter is necessary.

https://github.com/Zondax/rosetta-filecoin-lib/blob/431313ba6f4328d080f7a2e143da4205bbf86172/construction_api.go#L54

**Comment by jleni** [comment]
@raynaudoe is this still relevant?

**Comment by raynaudoe** [comment]
The requirement was never confirmed, we can close this.
