### ISSUE TITLE
destinationActorID question

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-lib#46]
When constructing msig transactions, we need to supply destinationActorID as `cid.CID`. However `construction/metadata` returns destinationActorID as string. So we need to parse string into cid.CID. I would like to see if we can change the interface to take string instead of cid.CID as destinationActorID. Otherwise, I am exploring the following way to parseString

```
        destinationActorID, err := cid.Parse(actorMetadata.DestinationActorID)
	if err != nil {
		return nil, errors.Wrap(err,
			fmt.Sprintf(
				"unable to parse destinationActorId to Cid: %s",
				actorMetadata.DestinationActorID,
			),
		)
	}
```

Is this the right approach? I do see this is a v2 cid.CID. So not sure if this the right way to do it.

**Comment by jleni** [comment]
@rllola @raynaudoe  is this something we can close?

**Comment by raynaudoe** [comment]
I think this one was discussed on Slack. We can close this for now.
