### ISSUE TITLE
Unrecognized `MultisigActorCodeID`

### ISSUE THREAD

**Issue by mallsk23** [Zondax/rosetta-filecoin-lib#69]
I've created a multisig address using `Lotus v1.5.0` with the signers of `f1bj7n6xidy5vudkmdfoqbrb74chibp3ip3fmvi6y` and `f16frpzretewu4uai4fyzc7f3wzw2paokdcf5ikhq` , only requiring 1 signer to sign.

```
lotus msig create --required=1 f1bj7n6xidy5vudkmdfoqbrb74chibp3ip3fmvi6y f16frpzretewu4uai4fyzc7f3wzw2paokdcf5ikhq
------
Created new multisig:  t01820 t27qlvkuwgnns7csuqq2rjpv3aeyuvogjhxay6fsq
```

I funded this multisig using the https://faucet.calibration.fildev.network/ faucet.

After funding I hit the Rosetta `/account/balance` endpoint, and we're able to see it's balance, confirming that it's registered on chain:

```
{
    "block_identifier": {
        "index": 24037,
        "hash": "0171a0e40220ca8da63290ab0ea6dbb37523ffda07855c1cc55d67e18617f29063f20889ef52"
    },
    "balances": [
        {
            "value": "500000000000000000000",
            "currency": {
                "symbol": "FIL",
                "decimals": 18
            }
        }
    ],
    "metadata": {
        "nonce": "0"
    }
}
```

After hitting the `/construction/metadata` endpoint with the `idSender` of `f1bj7n6xidy5vudkmdfoqbrb74chibp3ip3fmvi6y` and `idReceiver` of `t01820` (or even `t27qlvkuwgnns7csuqq2rjpv3aeyuvogjhxay6fsq`), we receive the following response:

```
{
    "metadata": {
        "chainID": "calibrationnet",
        "destinationActorId": "bafkqadtgnfwc6mzpnv2wy5djonuwo",
        "gasFeeCap": "200104",
        "gasLimit": 569335,
        "gasPremium": "199992",
        "nonce": 2
    }
}
```

When we invoke the `ConstructMultisigPayment` method to get the unsigned transaction, we receive the following [error](https://github.com/Zondax/rosetta-filecoin-lib/blob/3b15fa25b73febba04396a7c3eb1963ef1cc5152/construction_impl.go#L253) <- I've linked to the code:

`this actor id is not supported: errorString null`

Going through the same flow with a different multisig we receive the same error and the same `destinationActorID` of `bafkqadtgnfwc6mzpnv2wy5djonuwo`.

Note, other people have been encountering the exact same destinationActorID of `bafkqadtgnfwc6mzpnv2wy5djonuwo` on calibrationnet, and this issue is a reported one in the Filecoin / Lotus repo here: https://github.com/filecoin-project/lotus/issues/5662#issue-814010981

**Comment by jleni** [comment]
This was resolved as part of the proxy 1.500.0 release
https://github.com/Zondax/rosetta-filecoin-lib/releases/tag/v1.500.0
