### ISSUE TITLE
Base64 representation of unsigned transactions

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-lib#9]
Can we update the `ConstructPayment` method to return base64 encoded unsigned transaction instead of raw json?
- [interface](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_api.go#L23) 
- [Implementation](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_impl.go#L130) 

Can we update the `ConstructMultisigPayment` method to return base64 encoded unsigned transaction instead of raw json?
- [interface](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_api.go#L29) 
- [Implementation](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_impl.go#L185) 

Can we update the `ConstructSwapAuthorizedParty` method to return base64 encoded unsigned transaction instead of raw json?
- [interface](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_api.go#L35) 
- [Implementation](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_impl.go#L241)

**Comment by rllola** [comment]
@qiwu7 Do you want the want base64 string of the serialized unsigned transaction ? My guess is that you don't want to have base64 string of the raw json... but I lack of context to make an educated guess.
